config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todos
  patch 'todos/:id/update_status', :to => 'todos#update_status', as: :update_status

  resources :projects do
    get  'add_developers', on: :member
    patch 'save_developers', on: :member
  end
  get 'projects/:id/graph', :to => 'projects#graph', as: :project_graph
  get 'graphs', to: 'dashboards#graphs', as: :graphs
  get "project_todo_list", to: 'dashboards#project_todo_list', as: :project_todo_list
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "dashboards#developers_todo_list"
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :todos
  has_and_belongs_to_many :users
  validates :name, presence: true

  def team_members
    users.map(&:full_name).join(',') rescue ''
  end

  def project_name
    name.titleize
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource
  before_action :set_project, only: [:graph, :show, :edit, :update, :destroy, :add_developers, :save_developers]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
    end
  end

  def add_developers
    @users  = User.all.where("is_admin = ?", false)
  end

  def save_developers
    selected_users = []
    params[:project][:user_ids].each {|id| selected_users << id.to_i if id.to_i> 0 }
    @project.users.delete_all
    params[:project][:user_ids].each do|user_id|
      user = User.find(user_id) rescue nil
      @project.users
      @project.users << user if (user.present? && !@project.users.include?(user))
    end
    respond_to do |format|
      if @project.errors.blank?
        format.html { redirect_to projects_path, notice: 'Project\'s developers were successfully added.' }
      else
        format.html { render :add_developers }
      end
    end
  end
  def graph
     graph = @project.todos.joins(:todo_status).group("todo_statuses.name").count.to_a rescue []
     render json: { status: 200, data: graph, title: @project.name, id: @project.id  }
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end
    def developers
      params.require
    end
end

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :class => "form-horizontal project" } do |f| %>

  <% if @project.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projects_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/projects/add_developers.html.erb
<%= form_for @project, url: save_developers_project_path(@project), :html => { :class => "form-horizontal project" } do |f| %>

  <% if @project.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :developers, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= select(:project,:user_ids,@users.collect {|r| [r.name.titleize, r.id]},{:selected => @project.users.collect {|r| r.id}},:multiple => true) %>   
    </div>
    <%=f.error_span(:developers) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projects_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/graph.html.erb
<html>
  <head>
    <!--Load the AJAX API-->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">

      // Load the Visualization API and the piechart package.
      google.charts.load('current', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.charts.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table, 
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {

      // Create the data table.
      var data = new google.visualization.DataTable();
      data.addColumn('string', 'Status');
      data.addColumn('number', 'Count');
      //debugger
      data.addRows(data);

      // Set chart options
      var options = {'title': title,
                     'width':400,
                     'height':300};

      // Instantiate and draw our chart, passing in some options.
      var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
      chart.draw(data, options);
    }
    </script>
  </head>

  <body>
    <div id="chart_div" style="width:400; height:300"></div>
  </body>
  <script type="text/javascript">
  </script>
</html>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<% if can? :manage, Project %>
  <div class="row">
    <div class="col-12">        
      <%= link_to t('.new', :default => t("helpers.links.new")),
                  new_project_path,
                  :class => 'btn btn-xs btn-primary' %> |       
      <%= link_to 'Add Todo',
                  new_todo_path,
                  :class => 'btn  btn-xs btn-info' %>
    </div>
  </div>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th>Team Members</th>
      <% if can? :manage, Project %>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.id %></td>
        <td><%= link_to project.name.titleize, project_path(project) %></td>
        <td><%= project.team_members %></td>
        <% if can? :manage, project %>
          <td>
            <%= link_to "add_developers", add_developers_project_path(project.id), :class => 'btn btn-xs btn-primary' %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_project_path(project), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        project_path(project),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @project.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              projects_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_project_path(@project), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              project_path(@project),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>