config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todos
  patch 'todos/:id/update_status', :to => 'todos#update_status', as: :update_status

  resources :projects do
    get  'add_developers', on: :member
    patch 'save_developers', on: :member
  end
  get 'projects/:id/graph', :to => 'projects#graph', as: :project_graph
  get 'graphs', to: 'dashboards#graphs', as: :graphs
  get "project_todo_list", to: 'dashboards#project_todo_list', as: :project_todo_list
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "dashboards#developers_todo_list"
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :project
  belongs_to :user
  belongs_to :todo_status

  validates :title, :description, :due_date, presence: true
  validate :past_due_date, on: :create
  before_validation :set_status_as_new, on: :create
  scope :todo_by_status_id, ->(todo_status_id) {where(todo_status_id: todo_status_id)}

  private
    def past_due_date
      if due_date.present? && due_date < Date.today
        errors.add(:due_date, "can't be in the past")
      end
    end
   def set_status_as_new
     self.todo_status_id = TodoStatus.find_by_name("new").id
   end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  load_and_authorize_resource except: :update_status
  skip_authorization_check only: :update_status
  before_action :set_todo, only: [:show, :edit, :update, :destroy, :update_status]
  before_action :set_projects_and_users, only: [:new, :edit, :create, :update]

  def index
    @todos = current_user.is_admin? ? Todo.all : current_user.todos
  end

  def show
  end


  def new
    @todo = Todo.new
  end

  def edit
  end

  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
    end
  end

  def update_status
    if @todo.update_attributes(todo_params)
      data = (todo_params.key?("user_id") ? @todo.user.name : @todo.todo_status.name.capitalize).titleize rescue ''
      render json: { status: 200, data: data, message: "Status updated successfully."}
    else
      render json: {status: 201, message: @todo.errors.full_messages.join(",")}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end
    
    def set_projects_and_users
      @projects = Project.all
      @users = User.developers
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :description, :due_date, :todo_status_id, :project_id, :user_id)
    end
end

app/views/todos/_form.html.erb
<%= form_for @todo, :html => { :class => "form-horizontal todo" } do |f| %>

  <% if @todo.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @todo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :due_date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_select :due_date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:due_date) %>
  </div>
  <div class="form-group">
    <%= f.label :project_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :project_id, options_for_select(@projects.collect { | project | [project.name, project.id] }, @todo.project_id), {}, {:class => 'form-control'} %>
    </div>
    <%=f.error_span(:project_id) %>
  </div>
  <div class="form-group">
    <%= f.label :assign_to, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :user_id, options_for_select(@users.collect { | user | [user.name, user.id] }, @todo.user_id), {}, {:class => 'form-control'} %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                todos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/todos/edit.html.erb
<%- model_class = Todo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/todos/index.html.erb
<%- model_class = Todo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <% if can? :manage, Todo %>
    <%= link_to t('.new', :default => t("helpers.links.new")),
                new_todo_path,
                :class => 'btn btn-primary' %>
  <% end %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:due_date) %></th>
      <th><%= model_class.human_attribute_name(:todo_status_id) %></th>
      <th>Project</th>
      <th>Developer</th>
      <th>Mark As</th>
      <%if can? :manage, Todo%>
        <th>Assign To</th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <%end%>
    </tr>
  </thead>
  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.id %></td>
        <td><%= link_to todo.title, todo_path(todo) %></td>
        <td><%= todo.description %></td>
        <td><%= todo.due_date.strftime("%b %d %Y") %></td>
        <td id="todo<%=todo.id%>_todo_status_id"><%= todo.todo_status.name.titleize.capitalize %></td>
        <td><%= todo.project.name.titleize %></td>
        <td id="todo<%=todo.id%>_user_id"><%= todo.user.name.titleize %></td>
        <td>
          <%=select_tag :todo_status_id, options_for_select(TodoStatus.all.collect { | todo_status | [todo_status.name.capitalize.titleize, todo_status.id] }, todo.todo_status_id), prompt: "--select status--", "data-todo-id": todo.id, onchange: "update_status(this)"%>
        </td>
        <%if can? :manage, todo%>
          <td>
            <%=select_tag :user_id, options_for_select(todo.project.users.collect { | user | [user.name.titleize, user.id] }, todo.user_id), prompt: "--select develpeor--", "data-todo-id": todo.id, onchange: "update_status(this)"%>
          </td>
          <td>              
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_todo_path(todo), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        todo_path(todo),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          </td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
<script type="text/javascript">
  function update_status(element){
    todo_id = element.getAttribute("data-todo-id")
    data_param = element.getAttribute("id")
    data = {}
    data[data_param] = element.value

    data_td = $("#todo"+todo_id+"_"+data_param)
    if (todo_id != ""){
      $.ajax({
        url: 'todos/'+todo_id+'/update_status/',
        type: 'patch',
        dataType: 'json',
        data: {todo: data},
        success: function (response) {
          data_td.text(response.data)
          alert(response.message)
        },
        error: function() {
          alert("Something went wrong!")
        }
      });
    }
  }
</script>

app/views/todos/new.html.erb
<%- model_class = Todo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/todos/show.html.erb
<%- model_class = Todo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @todo.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @todo.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:due_date) %>:</strong></dt>
  <dd><%= @todo.due_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @todo.todo_status.name.titleize %></dd>
  <dt><strong><%= model_class.human_attribute_name(:project_id) %>:</strong></dt>
  <dd><%= @todo.project.name.titleize %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @todo.user.name.titleize %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              todos_path, :class => 'btn btn-default'  %>
<%if can? :manage, @todo%>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_todo_path(@todo), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                todo_path(@todo),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
<%end%>