config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todos
  patch 'todos/:id/update_status', :to => 'todos#update_status', as: :update_status

  resources :projects do
    get  'add_developers', on: :member
    patch 'save_developers', on: :member
  end
  get 'projects/:id/graph', :to => 'projects#graph', as: :project_graph
  get 'graphs', to: 'dashboards#graphs', as: :graphs
  get "project_todo_list", to: 'dashboards#project_todo_list', as: :project_todo_list
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "dashboards#developers_todo_list"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ProjectManagement" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144', skip_pipeline: true %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114', skip_pipeline: true %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72', skip_pipeline: true %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', skip_pipeline: true %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon', skip_pipeline: true %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%=root_path%>">ProjectManagement</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <%if current_user.is_admin? %>
                <li>
                  <%= link_to('Project-Wise-Status', project_todo_list_path) %>        
                </li>
                <li>
                  <%= link_to('Graphs', graphs_path) %>        
                </li>
                <li>
                  <%= link_to('Projects', projects_path) %>        
                </li>
              <%end%>
              <li>
                <%= link_to('Todos', todos_path) %>        
              </li>
              <li>
                <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
              </li>
            <% else %>
              <li>
              <%= link_to('Login', new_user_session_path) %>  
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->


    </div> <!-- /container -->
  </body>
</html>